# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faxCheck.ui'
#
# Created: Fri Feb 27 14:53:37 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 213)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.configBox = QtWidgets.QGroupBox(self.centralwidget)
        self.configBox.setGeometry(QtCore.QRect(2, 0, 396, 168))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configBox.sizePolicy().hasHeightForWidth())
        self.configBox.setSizePolicy(sizePolicy)
        self.configBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.configBox.setObjectName("configBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.configBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.checkIntervalLabel = QtWidgets.QLabel(self.configBox)
        self.checkIntervalLabel.setObjectName("checkIntervalLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkIntervalLabel)
        self.dirToMonitorLabel = QtWidgets.QLabel(self.configBox)
        self.dirToMonitorLabel.setObjectName("dirToMonitorLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dirToMonitorLabel)
        self.dirToMonitorLineEdit = QtWidgets.QLineEdit(self.configBox)
        self.dirToMonitorLineEdit.setMaxLength(1024)
        self.dirToMonitorLineEdit.setObjectName("dirToMonitorLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dirToMonitorLineEdit)
        self.lastMTimeLabel = QtWidgets.QLabel(self.configBox)
        self.lastMTimeLabel.setObjectName("lastMTimeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lastMTimeLabel)
        self.configFileLabel = QtWidgets.QLabel(self.configBox)
        self.configFileLabel.setObjectName("configFileLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.configFileLabel)
        self.checkIntervalLineEdit = QtWidgets.QLineEdit(self.configBox)
        self.checkIntervalLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.checkIntervalLineEdit.setMaxLength(3)
        self.checkIntervalLineEdit.setObjectName("checkIntervalLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkIntervalLineEdit)
        self.lastMTimeLineEdit = QtWidgets.QLineEdit(self.configBox)
        self.lastMTimeLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lastMTimeLineEdit.setReadOnly(True)
        self.lastMTimeLineEdit.setObjectName("lastMTimeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lastMTimeLineEdit)
        self.configFileLineEdit = QtWidgets.QLineEdit(self.configBox)
        self.configFileLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.configFileLineEdit.setReadOnly(True)
        self.configFileLineEdit.setObjectName("configFileLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.configFileLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.updatePushButton = QtWidgets.QPushButton(self.configBox)
        self.updatePushButton.setObjectName("updatePushButton")
        self.verticalLayout.addWidget(self.updatePushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkIntervalLineEdit, self.dirToMonitorLineEdit)
        MainWindow.setTabOrder(self.dirToMonitorLineEdit, self.lastMTimeLineEdit)
        MainWindow.setTabOrder(self.lastMTimeLineEdit, self.configFileLineEdit)
        MainWindow.setTabOrder(self.configFileLineEdit, self.updatePushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "faxCheck"))
        self.configBox.setTitle(_translate("MainWindow", "Configuration"))
        self.checkIntervalLabel.setText(_translate("MainWindow", "Check Interval:"))
        self.dirToMonitorLabel.setText(_translate("MainWindow", "Directory to Monitor:"))
        self.dirToMonitorLineEdit.setStatusTip(_translate("MainWindow", "New faxes created in this directory"))
        self.lastMTimeLabel.setText(_translate("MainWindow", "Last mtime:"))
        self.configFileLabel.setText(_translate("MainWindow", "Config File:"))
        self.checkIntervalLineEdit.setStatusTip(_translate("MainWindow", "Time interval between checking for new faxes"))
        self.updatePushButton.setText(_translate("MainWindow", "Update"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Exit faxCheck"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

